path: automations
title: Automations
icon: mdi:home-automation
cards:
  - type: entities
    title: Automations
    show_header_toggle: true
    entities:
      - automation.livingroom_light_on_before_sunset
      - automation.outside_light_on_at_sunset
      - automation.hall_light_on_when_opening_front_door
      - automation.hall_light_on_when_movement
      - automation.hall_light_off_when_no_movement
      - automation.set_sleep_mode_at_night
  - type: entities
    title: Notifications
    show_header_toggle: true
    entities:
      - automation.notification_on_restart
      - automation.high_co2_levels
      - automation.high_freezer_temperature
      - automation.high_inside_temperature
      - automation.low_inside_temperature
      - automation.public_ip_change
